### PR TITLE
master

### PR DESCRIPTION
**Pull request by marcosdiez**
Hi!

In order to make cbwin more user friendly, I added support to a --help parameter.

### CODE REVIEW

**Comment by xilun** [comment]
Many thanks for this patch!
Can you fix the following before integration:
- the example with `wrun` uses the `wcmd` command
- start.exe does not exist, the start command is actually a built-in of cmd.

**Comment by marcosdiez** [comment]
done :)

**Comment by xilun** [comment]
Almost perfect, but still: "as if one were using start.exe" <-- start.exe really does not exist. I just rechecked on my whole HD, I do not have a single start.exe. `start` is an ~~internal~~ built-in command of `cmd`, like `cd` is.

**Comment by marcosdiez** [comment]
ha!
you are right!!!

my bad.
I guess it used to exist in Windows95....
anyway... fixing it right now

Marcos Diez

**Comment by marcosdiez** [comment]
done

**Comment by xilun** [comment]
Perfect!
Thanks again :)

**Pull request merged**
